// <auto-generated />
namespace ConsoleApp_EF_CF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Coursetblcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Coursetblcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202204040617049_Course tbl create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
